# Generated by Django 4.0.1 on 2022-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_Data',
            field=models.DateTimeField(),
        ),
    ]
