# Generated by Django 4.0.1 on 2022-01-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_Name',
            new_name='user_Name',
        ),
    ]
